package connecterrors

import (
	"fmt"
	"sort"
	"sync"
	"sync/atomic"
	"time"

	"connectrpc.com/connect"
)

// Error code constants for common RPC error scenarios.
// These are auto-generated by protoc-gen-connect-errors-go or defined manually.
const (
	// ErrNotFound indicates the requested resource was not found.
	ErrNotFound ErrorCode = "ERROR_NOT_FOUND"

	// ErrInvalidArgument indicates a client-supplied argument was invalid.
	ErrInvalidArgument ErrorCode = "ERROR_INVALID_ARGUMENT"

	// ErrAlreadyExists indicates an attempt to create a resource that already exists.
	ErrAlreadyExists ErrorCode = "ERROR_ALREADY_EXISTS"

	// ErrPermissionDenied indicates the caller lacks permission for the operation.
	ErrPermissionDenied ErrorCode = "ERROR_PERMISSION_DENIED"

	// ErrUnauthenticated indicates the request lacks valid authentication credentials.
	ErrUnauthenticated ErrorCode = "ERROR_UNAUTHENTICATED"

	// ErrInternal indicates an unexpected internal server error.
	ErrInternal ErrorCode = "ERROR_INTERNAL"

	// ErrUnavailable indicates the service is currently unavailable.
	ErrUnavailable ErrorCode = "ERROR_UNAVAILABLE"

	// ErrDeadlineExceeded indicates the operation timed out.
	ErrDeadlineExceeded ErrorCode = "ERROR_DEADLINE_EXCEEDED"

	// ErrResourceExhausted indicates some resource has been exhausted (e.g. rate limit).
	ErrResourceExhausted ErrorCode = "ERROR_RESOURCE_EXHAUSTED"

	// ErrFailedPrecondition indicates the operation was rejected because
	// the system is not in a state required for execution.
	ErrFailedPrecondition ErrorCode = "ERROR_FAILED_PRECONDITION"

	// ErrAborted indicates the operation was aborted (e.g. concurrency conflict).
	ErrAborted ErrorCode = "ERROR_ABORTED"

	// ErrOutOfRange indicates a value is out of the accepted range.
	ErrOutOfRange ErrorCode = "ERROR_OUT_OF_RANGE"

	// ErrUnimplemented indicates the operation is not implemented or supported.
	ErrUnimplemented ErrorCode = "ERROR_UNIMPLEMENTED"

	// ErrCanceled indicates the operation was canceled by the caller.
	ErrCanceled ErrorCode = "ERROR_CANCELED"

	// ErrDataLoss indicates unrecoverable data loss or corruption.
	ErrDataLoss ErrorCode = "ERROR_DATA_LOSS"
)

// Error represents a Connect RPC error definition with template support.
// It maps a semantic error code to a Connect status code and message template.
type Error struct {
	// ErrorCode is the unique error identifier (e.g. "ERROR_NOT_FOUND").
	ErrorCode ErrorCode

	// MessageTpl is a message template with {{placeholder}} syntax.
	MessageTpl string

	// StatusCode is the Connect RPC status code for this error.
	StatusCode connect.Code

	// Retryable indicates whether the client should retry the request.
	Retryable bool

	// RetryDelay specifies the delay to use in google.rpc.RetryInfo.
	// If zero, the default (zero delay) is used. Only meaningful when Retryable is true.
	RetryDelay time.Duration
}

// writeMu protects Registry writes. Reads are lock-free via atomic.Value.
var writeMu sync.Mutex

// registryVal stores an immutable map[ErrorCode]Error snapshot.
// Reads are lock-free (atomic load). Writes copy-on-write under writeMu.
var registryVal atomic.Value

// defaultErrors is the default error definitions. This is used to initialize registryVal.
// After init, use Lookup/Register/RegisterAll to interact with the registry.
var defaultErrors = map[ErrorCode]Error{
	ErrNotFound: {
		ErrorCode:   ErrNotFound,
		MessageTpl:  "Resource not found",
		StatusCode:  connect.CodeNotFound,
		Retryable:   false,
	},
	ErrInvalidArgument: {
		ErrorCode:   ErrInvalidArgument,
		MessageTpl:  "Invalid argument",
		StatusCode:  connect.CodeInvalidArgument,
		Retryable:   false,
	},
	ErrAlreadyExists: {
		ErrorCode:   ErrAlreadyExists,
		MessageTpl:  "Resource already exists",
		StatusCode:  connect.CodeAlreadyExists,
		Retryable:   false,
	},
	ErrPermissionDenied: {
		ErrorCode:   ErrPermissionDenied,
		MessageTpl:  "Permission denied",
		StatusCode:  connect.CodePermissionDenied,
		Retryable:   false,
	},
	ErrUnauthenticated: {
		ErrorCode:   ErrUnauthenticated,
		MessageTpl:  "Authentication required",
		StatusCode:  connect.CodeUnauthenticated,
		Retryable:   false,
	},
	ErrInternal: {
		ErrorCode:   ErrInternal,
		MessageTpl:  "Internal server error",
		StatusCode:  connect.CodeInternal,
		Retryable:   false,
	},
	ErrUnavailable: {
		ErrorCode:   ErrUnavailable,
		MessageTpl:  "Service unavailable",
		StatusCode:  connect.CodeUnavailable,
		Retryable:   true,
	},
	ErrDeadlineExceeded: {
		ErrorCode:   ErrDeadlineExceeded,
		MessageTpl:  "Deadline exceeded",
		StatusCode:  connect.CodeDeadlineExceeded,
		Retryable:   true,
	},
	ErrResourceExhausted: {
		ErrorCode:   ErrResourceExhausted,
		MessageTpl:  "Resource exhausted",
		StatusCode:  connect.CodeResourceExhausted,
		Retryable:   true,
	},
	ErrFailedPrecondition: {
		ErrorCode:   ErrFailedPrecondition,
		MessageTpl:  "Failed precondition",
		StatusCode:  connect.CodeFailedPrecondition,
		Retryable:   false,
	},
	ErrAborted: {
		ErrorCode:   ErrAborted,
		MessageTpl:  "Operation aborted",
		StatusCode:  connect.CodeAborted,
		Retryable:   true,
	},
	ErrOutOfRange: {
		ErrorCode:   ErrOutOfRange,
		MessageTpl:  "Value out of range",
		StatusCode:  connect.CodeOutOfRange,
		Retryable:   false,
	},
	ErrUnimplemented: {
		ErrorCode:   ErrUnimplemented,
		MessageTpl:  "Operation not implemented",
		StatusCode:  connect.CodeUnimplemented,
		Retryable:   false,
	},
	ErrCanceled: {
		ErrorCode:   ErrCanceled,
		MessageTpl:  "RPC canceled",
		StatusCode:  connect.CodeCanceled,
		Retryable:   false,
	},
	ErrDataLoss: {
		ErrorCode:   ErrDataLoss,
		MessageTpl:  "Unrecoverable data loss",
		StatusCode:  connect.CodeDataLoss,
		Retryable:   false,
	},
}

// Register adds or updates an error definition in the global Registry.
// It is safe for concurrent use. Uses copy-on-write for lock-free reads.
//
// Example:
//
//	connecterrors.Register(connecterrors.Error{
//	    ErrorCode:   "ERROR_CUSTOM",
//	    MessageTpl:  "Custom error: {{detail}}",
//	    StatusCode:  connect.CodeInternal,
//	    Retryable:   false,
//	})
func Register(err Error) {
	if err.ErrorCode == "" {
		return
	}
	writeMu.Lock()
	defer writeMu.Unlock()
	current := loadRegistry()
	updated := make(map[ErrorCode]Error, len(current)+1)
	for k, v := range current {
		updated[k] = v
	}
	updated[err.ErrorCode] = err
	registryVal.Store(updated)
}

// RegisterAll adds multiple error definitions to the global Registry.
// It is safe for concurrent use. Uses copy-on-write for lock-free reads.
func RegisterAll(errs []Error) {
	writeMu.Lock()
	defer writeMu.Unlock()
	current := loadRegistry()
	updated := make(map[ErrorCode]Error, len(current)+len(errs))
	for k, v := range current {
		updated[k] = v
	}
	for _, err := range errs {
		if err.ErrorCode != "" {
			updated[err.ErrorCode] = err
		}
	}
	registryVal.Store(updated)
}

// Lookup retrieves an error definition from the Registry by its code.
// Lock-free: uses atomic load, no mutex overhead.
//
// Example:
//
//	e, ok := connecterrors.Lookup(connecterrors.ErrNotFound)
func Lookup(code ErrorCode) (Error, bool) {
	m := loadRegistry()
	e, ok := m[code]
	return e, ok
}

// MustLookup retrieves an error definition by code and panics if not found.
// Use this only during initialization or in tests.
func MustLookup(code ErrorCode) Error {
	e, ok := Lookup(code)
	if !ok {
		panic(fmt.Sprintf("connecterrors: unknown error code %q", code))
	}
	return e
}

// Codes returns all registered error codes in sorted order.
// Useful for debugging, documentation, or building admin UIs.
func Codes() []string {
	m := loadRegistry()
	codes := make([]string, 0, len(m))
	for k := range m {
		codes = append(codes, string(k))
	}
	sort.Strings(codes)
	return codes
}

// ResetRegistry restores the registry to the default error definitions.
// This is primarily useful for testing: it clears any custom registrations
// and reloads the built-in defaults. Safe for concurrent use.
func ResetRegistry() {
	writeMu.Lock()
	defer writeMu.Unlock()
	registryVal.Store(defaultErrors)
}

// loadRegistry returns the current immutable registry snapshot.
func loadRegistry() map[ErrorCode]Error {
	v := registryVal.Load()
	if v == nil {
		return nil
	}
	return v.(map[ErrorCode]Error)
}

func init() {
	registryVal.Store(defaultErrors)
}
